-- db/init.sql
CREATE TABLE IF NOT EXISTS users (
    id VARCHAR(50) PRIMARY KEY,
    pw VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS pantry (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id VARCHAR(50),
    item_name VARCHAR(100) NOT NULL,
    item_emoji VARCHAR(10) DEFAULT '📦',
    expiry_date DATE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);